sudo: false
language: node_js
node_js:
  - stable
  - "5.1"
  - "5"
  - "4.2"
  - "4.1"
  - "4.0"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@3
before_script:
  - npm prune
script:
  - npm run test:cov
after_script:
  - npm run coveralls:upload